name: Setup

description: Sets up PHP and Composer

runs:
  using: composite
  steps:
    - name: Setup Cache Environment
      id: ext-cache
      uses: shivammathur/cache-extensions@v1
      with:
        php-version: ${{ env.PHP_VERSION }}
        extensions: ${{ env.PHP_EXTENSIONS }}
        key: ${{ env.CACHE_KEY }}

    - name: Cache PHP Extensions
      uses: actions/cache@v4
      with:
        path: ${{ steps.ext-cache.outputs.dir }}
        key: ${{ steps.ext-cache.outputs.key }}
        restore-keys: ${{ steps.ext-cache.outputs.key }}

    - name: Setup PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.PHP_VERSION }}
        extensions: ${{ env.PHP_EXTENSIONS }}
        tools: composer:v2

    - name: Get Composer Cache dir
      id: composer-cache-dir
      run: echo dir=$(composer config cache-files-dir) >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache Dependencies
      uses: actions/cache@v4
      with:
        key: composer-cache-${{ hashFiles('**/composer.lock') }}
        path: ${{ steps.composer-cache-dir.outputs.dir }}
        restore-keys: composer-cache-
