services:
  mysql:
    image: mysql:8.1
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:13
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mysql_data:
  postgres_data:
