name: Laravel Pint

on:
  pull_request

jobs:
  laravel-pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2

      - name: Install Laravel Pint
        run: composer global require laravel/pint

      - name: Run Pint
        run: pint

      - name: Push Changes Back to the Repository
        run: |
          git config user.name "gh-actions[bot]"
          git config user.email "gh-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Laravel Pint"
          get push
