name: Tests

on:
  pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7.4
        ports:
          - 6379:6379
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7

      - name: Setup cache environment
        id: ext-cache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: '8.3'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, gd, redis, igbinary, msgpack, lzf, zstd, lz4, memcached, gmp, :php-psr
          key: extension-cache-v1

      - name: Cache Extensions
        uses: actions/cache@v4
        with:
          path: ${{ steps.ext-cache.outputs.dir }}
          key: ${{ steps.ext-cache.outputs.key }}
          restore-keys: ${{ steps.ext-cache.outputs.key }}

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, gd, redis, igbinary, msgpack, lzf, zstd, lz4, memcached, gmp, :php-psr

      - name: Get Composer Cache dir
        id: composer-cache-dir
        run: echo dir=$(composer config cache-files-dir) >> $GITHUB_OUTPUT

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          key: composer-cache-${{ hashFiles('**/composer.lock') }}
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          restore-keys: composer-cache-

      - name: Install Dependencies
        run: composer install -q --no-interaction

      - name: Set Up Environment
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Tests
        run: php artisan test --compact
